

export enum MessageType {
    FILE_STARTED = 'FILE_STARTED',
    FILE_ENDED = 'FILE_ENDED',
    CLASS_STARTED = 'CLASS_STARTED',
    CLASS_ENDED = 'CLASS_ENDED',
    TEST_STARTED = 'TEST_STARTED',
    TEST_ENDED = 'TEST_ENDED'
}
